baseURL = "http://altamash-hi.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-us"
title = "My Portfolio Website"
theme = "hugo-lodi-theme"
# googleAnalytics = "UA-XXXXXXXX-Y"

[deployment.targets]

name = "awsbucket"
URL = "s3://altamash-hi/?region=us-east-1" #your bucket here

[params]
    # head theme color
    theme_color = ""

    # head description
    # This is what appears on the preview when posting this site on Facebook for example
    description = ""

    # head photo
    # This is what appears on the preview when posting this site on Facebook for example
    description_photo = "portfolio.jpg"

    # favicon image (512x512px), place this in the static/img folder
    favicon = "favicon.png"

    # logo image (204x204px), place this in the static/img folder
    # this appears on the top left of the navigation
    logo = "logo.png"

    # Facebook username
    # facebook = ""

    # Twitter username
    # twitter = "asdf"

    # Dribbble username
    # dribbble = ""

    # Medium username
    # medium = "asdf"

    # Github username
    github = "https://github.com/AltamashRafiq"
    
    # LinkedIn URL
    linkedin = "https://www.linkedin.com/in/altamashrafiq/"
    
    # Email
    email = "altamashrafiq@gmail.com"

    # Google Scholar URL
    # googlescholar = ""

[params.nav]
    enable = true

[params.hero]
    enable = true

    # Place this image in the static/img folder
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Altamash, a Data Scientist and Machine Learning Engineer."

    # Each element in this array makes a new <p> tag
    # You can write this text in markdown
    hero_right = [
    "Welcome to my personal website! I'm Altamash, a data scientist at __2nd Order Solutions__. I use cutting edge methods in machine learning and analytics to deliver impactful credit risk and lending solutions for financial institutions, banks, and fintechs.",
    "Originally from Pakistan, I came to the US to pursue both my Bachelor's and Master's degrees at __Duke University__. At Duke, I fell in love with statistical modeling and machine learning when I saw firsthand their potential for bringing transformational change in our world. Over the years, I have had many amazing opportunities to learn and grow as a data scientist through projects in cybersecurity, fraud detection, infectious disease research, and more.",
    "For an in depth view into my work, check out my featured projects below or visit my [GitHub](https://github.com/AltamashRafiq). I love to share ideas and connect with professionals in all data science adjacent fields so feel free to email me if you ever want to chat!"]

    # Link to your resume, place your PDF in the /static folder
    resume = "Resume_Altamash_Rafiq.pdf"

[params.process]
    enable = true
    title = "My Skills"
    #subtitle = "Data Science Specific"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
